name: Deploy VitePress Sites with pnpm

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: [docs, demo]
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install pnpm
        run: npm install -g pnpm@8

      - name: Install root dependencies
        run: pnpm install --frozen-lockfile

      - name: Build ${{ matrix.project }}
        working-directory: ${{ matrix.project }}
        run: |
          pnpm build
          mkdir -p ../dist/${{ matrix.project }}
          cp -R .vitepress/dist/* ../dist/${{ matrix.project }}/

      - name: Deploy to GH Pages
        if: matrix.project == 'docs'  # 只需执行一次
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          keep_files: true