name: Deploy VitePress Sites with pnpm

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: [docs, demo]
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'pnpm'

      # 关键修正：在每个矩阵任务中显式设置 pnpm
      - name: Install pnpm
        run: |
          corepack enable
          corepack prepare pnpm@8.15.4 --activate
          echo "$HOME/.local/share/pnpm" >> $GITHUB_PATH

      # 验证环境
      - name: Verify Environment
        run: |
          echo "PATH: $PATH"
          which pnpm
          pnpm -v

      - name: Install dependencies
        run: |
          pnpm install --frozen-lockfile

      - name: Build ${{ matrix.project }}
        working-directory: ${{ matrix.project }}
        run: |
          pnpm build
          mkdir -p ../dist/${{ matrix.project }}
          cp -R .vitepress/dist/* ../dist/${{ matrix.project }}/

      - name: Deploy to GH Pages
        if: matrix.project == 'docs'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          keep_files: true